language: python
before_script:
  - psql -c "alter role postgres with password 'postgres';" -U postgres
services:
  - postgresql
python:
  - "3.6"
script:
  - pip install -r requirements.txt
  - cd web_app
  - pytest
