language: python
addons:
  postgresql: "9.6"
before_script:
  - psql -c "alter role postgres with password 'postgres';" -U postgres
services:
  - postgresql
python:
  - "3.6"
script:
  - cd web_app
  - pytest
