language: python
addons:
  postgresql: "9.6"
before_install:
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt-get install -y nodejs
before_script:
  - psql -c "alter role postgres with password 'postgres';" -U postgres
services:
  - postgresql
python:
  - "3.6"
script:
  - cd web_app
  - pytest
  - cd ../front
  - npm i
  - npm test
